version: "3.9"
services:
  tb:
    build:
      context: .
      dockerfile: Dockerfile.tb
    container_name: tb_container
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./dags:/app/airflow/dags
      - ./logs:/app/airflow/logs
      - ./plugins:/app/airflow/plugins
      - ./start.sh:/app/start.sh
    ports:
      - "8080:8080"
    command: ["/bin/bash", "-c", "/app/start.sh"]
  api:
    build:
      context: .
      dockerfile: Dockerfile.API
    container_name: api_container
    ports:
      - "5000:5000"
